name: "Tag and Release"
description: "Automatically create version tag and GitHub release"

inputs:
  github-token:
    description: "GitHub token"
    required: true
  version-bump:
    description: "Version bump type"
    required: false
    default: "patch"
  artifacts:
    description: "Comma-separated list of artifacts to include in release"
    required: true

outputs:
  tag:
    description: "Created tag"
    value: ${{ steps.outputs.outputs.tag }}
  changelog:
    description: "Generated changelog"
    value: ${{ steps.outputs.outputs.changelog }}
  should-release:
    description: "Whether release should proceed"
    value: ${{ steps.outputs.outputs.should_release }}

runs:
  using: "composite"
  steps:
    - name: Bump version and push tag
      id: tag
      if: github.ref_name == 'main'
      uses: anothrNick/github-tag-action@1.67.0
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        WITH_V: true
        DEFAULT_BUMP: ${{ inputs.version-bump }}
        RELEASE_BRANCHES: main
        DRY_RUN: false
        VERBOSE: true
        INITIAL_VERSION: "1.0.0"
        TAG_CONTEXT: branch

    - name: Set outputs
      id: outputs
      shell: bash
      run: |
        if [ "${{ github.ref_name }}" = "main" ]; then
          echo "tag=${{ steps.tag.outputs.tag }}" >> $GITHUB_OUTPUT
          echo "changelog=${{ steps.tag.outputs.changelog }}" >> $GITHUB_OUTPUT
          echo "should_release=true" >> $GITHUB_OUTPUT
        else
          echo "tag=" >> $GITHUB_OUTPUT
          echo "changelog=" >> $GITHUB_OUTPUT
          echo "should_release=false" >> $GITHUB_OUTPUT
        fi

    - name: Download artifacts
      if: steps.outputs.outputs.should_release == 'true'
      uses: actions/download-artifact@v4
      with:
        path: ./release

    - name: Create GitHub Release
      if: steps.outputs.outputs.should_release == 'true' && steps.outputs.outputs.tag != ''
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.outputs.outputs.tag }}
        name: Release ${{ steps.outputs.outputs.tag }}
        body: |
          ## 🚀 Release ${{ steps.outputs.outputs.tag }}

          ### ✨ What's New
          ${{ steps.outputs.outputs.changelog }}

          ### 📦 Downloads
          - **Linux**: file-fusion-rename-linux
          - **Windows**: file-fusion-rename-windows.exe  
          - **macOS**: file-fusion-rename-macos

          ### 🔧 Installation
          1. Download the appropriate binary for your platform
          2. Make it executable (Linux/macOS): `chmod +x file-fusion-rename-*`
          3. Run the application

          ### 📝 Changelog
          For detailed changes, see the commit history.
        files: |
          ./release/file-fusion-rename-macos/file-fusion-rename-macos
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
