name: Build and Release Go GUI App

on:
  push:
    branches:
      - "**"
    tags:
      - "v*"
  pull_request:
    branches:
      - "**"

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"
      - name: Install GUI dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libdbusmenu-glib-dev \
            libayatana-appindicator3-dev \
            libayatana-indicator3-dev
      - name: Run tests
        run: go test -v ./...

  build:
    name: Build Applications
    needs: [test]
    if: always() && needs.test.result == 'success' && (github.ref_name == 'main' || startsWith(github.ref, 'refs/tags/'))
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Build Application
        uses: ./.github/actions/build
        with:
          go-version: "1.24"

  tag-and-release:
    name: Tag and Release
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: write

    if: github.ref_name == 'main' || startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag and Release
        uses: ./.github/actions/tag-and-release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version-bump: "patch"
          artifacts: "file-fusion-rename-linux,file-fusion-rename-windows.exe,file-fusion-rename-macos-intel,file-fusion-rename-macos-arm64"
