name: Build Go GUI App

on:
  push:
    branches:
      - main

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v5
        with:
          go-version: "1.20"
      - name: Install GTK
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev
      - name: Build Linux Binary
        run: |
          export CGO_ENABLED=1
          go build -ldflags="-s -w" -o go-file-fusion-rename-linux main.go
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: go-file-fusion-rename-linux
          path: go-file-fusion-rename-linux

  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v5
        with:
          go-version: "1.20"
      - name: Build Windows Binary
        run: |
          set CGO_ENABLED=1
          go build -ldflags="-s -w" -o go-file-fusion-rename.exe main.go
      - uses: actions/upload-artifact@v4
        with:
          name: go-file-fusion-rename-windows
          path: go-file-fusion-rename.exe

  build-macos:
    name: Build macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v5
        with:
          go-version: "1.20"
      - name: Build macOS Binary
        run: |
          export CGO_ENABLED=1
          go build -ldflags="-s -w" -o go-file-fusion-rename-macos main.go
      - uses: actions/upload-artifact@v4
        with:
          name: go-file-fusion-rename-macos
          path: go-file-fusion-rename-macos
